[workspace]
members = [
    "haitaka",
    "haitaka_types"
]
resolver = "2"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"

[profile.bench]
opt-level = 3
codegen-units = 1
lto = "fat"
